LibraryManagementSystem/Models/ErrorViewModel.cs
namespace LibraryManagementSystem.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LibraryManagementSystem/Controllers/HomeController.cs
using LibraryManagementSystem.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LibraryManagementSystem.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LibraryManagementSystem/Controllers/LibrarianController.cs
using DataAccessLayer.context;
using DataAccessLayer.entities;

using Microsoft.AspNetCore.Mvc;

namespace LibraryManagementSysytem.Controllers
{
    public class LibrarianController : Controller
    {
        private readonly ApplicationDbContext _db;
        public LibrarianController(ApplicationDbContext db)
        {
             _db = db;
        }
        public IActionResult Index()
        {
            List<Librarian> LibrarianList=_db.Librarians.ToList();
            return View(LibrarianList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Librarian lib)
        {
            //if(lib.First_Name.ToLower() == lib.DisplayOrder.Tostring)
            if (ModelState.IsValid)
            {
                _db.Librarians.Add(lib);
                _db.SaveChanges();
                TempData["Success"] = "تم الإضافة بنجاح";

                return RedirectToAction("Index");

            }
            return View();

        }
        public IActionResult Edit(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }
            Librarian? LibrarianfromDB = _db.Librarians.Find(id);
            //Librarian? LibrarianfromDB1 = _db.Librarians.FirstOrDefault(u=>u.ID==id);
            //Librarian? LibrarianfromDB2 = _db.Librarians.Where(u=>u.ID==id).FirstOrDefault();
            if (LibrarianfromDB==null)
            {
                return NotFound();
            }
            return View(LibrarianfromDB);
        }



        [HttpPost]
        public IActionResult Edit(Librarian lib)
        {
            //if(lib.First_Name.ToLower() == lib.DisplayOrder.Tostring)
            if (ModelState.IsValid)
            {
                _db.Librarians.Update(lib);
                _db.SaveChanges();
                TempData["Success"] = "تم تحديث البيانات بنجاح";

                return RedirectToAction("Index");

            }
            return View();

        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Librarian? LibrarianfromDB = _db.Librarians.Find(id);

            if (LibrarianfromDB == null)
            {
                return NotFound();
            }
            return View(LibrarianfromDB);
        }



        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePOST(int? id)
        {
                Librarian? Lib = _db.Librarians.Find(id);
                if (Lib == null)
                {
                    return NotFound();
                }
                _db.Librarians.Remove(Lib);
                _db.SaveChanges();
            TempData["Success"] = "تم الحذف بنجاح";
                return RedirectToAction("Index");
        }
    }
}

LibraryManagementSystem/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

LibraryManagementSystem/Views/Librarian/Create.cshtml
@using DataAccessLayer.entities
@model Librarian
<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ms-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white">Create Librarian</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">

        <form method="post" class="row">
            <div class="form-group">
                <div asp-validation-summary="All"></div>
                <label asp-for="First_Name" for="inputFirstName"></label>
                <input asp-for="First_Name" class="form-control" id="inputFirstName">
                <span asp-validation-for="First_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Last_Name" for="inputLastName"></label>
                <input asp-for="Last_Name" class="form-control" id="inputLastName">
                <span asp-validation-for="Last_Name" class="text-danger"></span>

            </div>
            <div class="form-group">
                <label asp-for="Email" for="exampleInputEmail1"></label>
                <input asp-for="Email" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                <span asp-validation-for="Email" class="text-danger"></span>

            </div>

            <div class="form-group">
                <label asp-for="Phone" for="inputPhone"></label>
                <input asp-for="Phone" class="form-control" id="inputPhone">
                <span asp-validation-for="Phone" class="text-danger"></span>

            </div>


            <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Check me out</label>
            </div>
            <div class="row">
                <div class="col-6 col-md-3">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>

                <div class="col-6 col-md-3">
                    <a asp-controller="Librarian" asp-action="Index" class="btn btn-secondary border form-control">
                        Back To List
                    </a>
                </div>
            </div>

        </form>
    </div>


</div>

LibraryManagementSystem/Views/Librarian/Delete.cshtml
@using DataAccessLayer.entities
@{
    ViewData["Title"] = "Edit";
}

@model Librarian

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ms-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white">Delete Librarian</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post">
            <input asp-for="ID" hidden />
            <div class="form-group">
                <div asp-validation-summary="All"></div>
                <label asp-for="First_Name" for="inputFirstName"></label>
                <input asp-for="First_Name" disabled class="form-control" id="inputFirstName">

            </div>
            <div class="form-group">
                <label asp-for="Last_Name" for="inputLastName"></label>
                <input asp-for="Last_Name" disabled class="form-control" id="inputLastName">


            </div>
            <div class="form-group">
                <label asp-for="Email" for="exampleInputEmail1"></label>
                <input asp-for="Email" disabled type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>


            </div>

            <div class="form-group">
                <label asp-for="Phone" for="inputPhone"></label>
                <input asp-for="Phone" disabled class="form-control" id="inputPhone">


            </div>


            <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Check me out</label>
            </div>
            <div class="row">
                <div class="col-6 col-md-3">
                    <button type="submit" class="btn btn-danger">Delete</button>
                </div>

                <div class="col-6 col-md-3">
                    <a asp-controller="Librarian" asp-action="Index" class="btn btn-secondary border form-control">
                        Back To List
                    </a>
                </div>
            </div>

        </form>

    </div>

LibraryManagementSystem/Views/Librarian/Edit.cshtml
@using DataAccessLayer.entities
@{
    ViewData["Title"] = "Edit";
}


@model Librarian
<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ms-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white">Edit Librarian</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post">
            <input asp-for="ID" hidden />
            <div class="form-group">
                <div asp-validation-summary="All"></div>
                <label asp-for="First_Name" for="inputFirstName"></label>
                <input asp-for="First_Name" class="form-control" id="inputFirstName">
                <span asp-validation-for="First_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Last_Name" for="inputLastName"></label>
                <input asp-for="Last_Name" class="form-control" id="inputLastName">
                <span asp-validation-for="Last_Name" class="text-danger"></span>

            </div>
            <div class="form-group">
                <label asp-for="Email" for="exampleInputEmail1"></label>
                <input asp-for="Email" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                <span asp-validation-for="Email" class="text-danger"></span>

            </div>

            <div class="form-group">
                <label asp-for="Phone" for="inputPhone"></label>
                <input asp-for="Phone" class="form-control" id="inputPhone">
                <span asp-validation-for="Phone" class="text-danger"></span>

            </div>


            <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Check me out</label>
            </div>
            <div class="row">
                <div class="col-6 col-md-3">
                    <button type="submit" class="btn btn-primary">Update</button>
                </div>

                <div class="col-6 col-md-3">
                    <a asp-controller="Librarian" asp-action="Index" class="btn btn-secondary border form-control">
                        Back To List
                    </a>
                </div>
            </div>

        </form>


    </div>

LibraryManagementSystem/Views/Librarian/Index.cshtml
@using DataAccessLayer.entities
@model List<Librarian>

<div class="container">
    
    <div class="row pt-4 pb-3">
        <div class="col-6">
            <h2 class="text-primary">
                Librarian List
            </h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Librarian" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i>Create New Librarian
            </a>
        </div>
    </div>
<table class="table table-hover table-dark">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Phone</th>
            <th scope="col"></th>
            
        </tr>
    </thead>
    <tbody>
        @foreach (var Lib in Model.OrderBy(u=>u.First_Name))
        {
            <tr>
                <th scope="row">@Lib.ID</th>
                <td>@Lib.First_Name  @Lib.Last_Name</td>
                <td>@Lib.Email</td>
                <td>@Lib.Phone</td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Librarian" asp-action="Edit" asp-route-id="@Lib.ID" class="btn btn-primary mx-2">
                                <i class="bi bi-pencil-square"></i> Edit
                        </a>
                            <a asp-controller="Librarian" asp-action="Delete" asp-route-id="@Lib.ID" class="btn btn-danger mx-2">
                                <i class="bi bi-trash3-fill"></i>Delete
                        </a>
                    </div>

                </td>

            </tr>
        }


    </tbody>
</table>
</div>

LibraryManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibraryManagementSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LibraryManagementSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LibraryManagementSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - LibraryManagementSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>